version: "3"
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    env_file:
      - docker.env
 
  medical-assistance-service:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-assistance-service

    env_file:
      - .env
    ports:
      - "4202:4202"
    depends_on:
      - postgres
    networks:
      - postgres
 
volumes:
  postgres:
    driver: local

networks:
  postgres:
    driver: bridge