version: "3"
services:
  api-gateway-service:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway-service

    volumes:
      - ./certs:/app/certs
    env_file:
      - .env
    ports:
      - "3000:3000"
    